ENTRAID_UUID_SAKSBEHANDLER: 611669fa-de5c-4dc2-a0e8-6041a019992a
ENTRAID_UUID_BESLUTTER: 59f26eef-0a4f-4038-bf46-3a5b2f252155
ENTRAID_UUID_EGEN_ANSATT: e750ceb5-b70b-4d94-b4fa-9d22467b786b
ENTRAID_UUID_KODE_7: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
ENTRAID_UUID_STIKKPROVE: e382880a-e12f-4d56-a92e-2283d7da43af
ENTRAID_UUID_TBD: f787f900-6697-440d-a086-d5bb56e26a9c
ENTRAID_UUID_NAIS_TBD: c0227409-2085-4eb2-b487-c4ba270986a3
ENTRAID_UUID_SPEIL_SAKSBEHANDLER_SELVSTENDIG_BETA: 08d345c6-e369-4065-b202-6209c9f31987
ENTRAID_UUID_SPEIL_RIKSREVISJONEN: 54273224-e40a-4e3d-b3cb-2219603058f9

# Kun dev grupper
ENTRAID_UUID_KODE_7_DEV: c811e9f4-26a6-43f9-b930-8c83365683a9 # 0000-AZ-speil-kode7-dev
ENTRAID_UUID_SPEIL_BESLUTTERE_DEV: dd4e2415-b68d-43a4-87b5-fe2ba5f1dc61
ENTRAID_UUID_SPEIL_BRUKERE_DEV: 317665ad-1402-458e-b8e6-9cb50afc1252
