schema: 'schema_til_bruk_fra_tester.graphql'
extensions:
  endpoints:
    spesialist-local:
      url: http://0.0.0.0:8080/graphql
      headers:
        # Lim inn token bak p√• linja under, men ikke commit det
        Authorization: Bearer
